// Generated by sdkgen go-cli target.
package main

import (
	"fmt"
	"strings"

	eng "github.com/boru-lang/boru/eng/go"
	sdk "github.com/voxgig-sdk/hubspot-automation-sdk/go"
)

// registerSDKWords installs three native boru words bound to the SDK:
// list / load / update. Each is declared with two overloads matching
// the signature  [query?:(Node or Scalar) entity:atom]:
//
//   [entity:Atom]            — no query (e.g. `list book`)
//   [query:Any entity:Atom]  — query is any Node or Scalar (e.g.
//                              `load {id:1} book`, `load 1 book`)
//
// The entity slot is /q-quoted so a bareword `book` parses as the
// Atom "book" rather than dispatching as an undefined word. Both
// overloads are all-forward (BarrierAllForward), so args are collected
// from the tokens following the word.
func registerSDKWords(r *eng.Registry, client *sdk.HubspotAutomationSDK) {
	for _, op := range []string{"list", "load", "update"} {
		op := op
		single := eng.Signature{
			Args:      []*eng.Type{eng.TAtom},
			QuoteArgs: map[int]bool{0: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				return runOp(client, op, nil, args[0])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		dual := eng.Signature{
			Args:      []*eng.Type{eng.TAny, eng.TAtom},
			QuoteArgs: map[int]bool{1: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				q := args[0]
				return runOp(client, op, &q, args[1])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		r.RegisterNativeFunc(eng.NativeFunc{
			Name:       op,
			Signatures: []eng.Signature{single, dual},
		})
	}
}

func runOp(client *sdk.HubspotAutomationSDK, op string, query *eng.Value, entityAtom eng.Value) ([]eng.Value, error) {
	entityName, err := eng.AsAtom(entityAtom)
	if err != nil {
		return nil, fmt.Errorf("%s: entity argument is not an atom: %w", op, err)
	}
	ent, err := entityFor(client, entityName)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	var arg map[string]any
	if query != nil {
		arg, err = queryToMap(*query)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", op, err)
		}
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(arg, nil)
	case "load":
		result, err = ent.Load(arg, nil)
	case "update":
		result, err = ent.Update(arg, nil)
	default:
		return nil, fmt.Errorf("unknown op %q", op)
	}
	if err != nil {
		return nil, err
	}
	return []eng.Value{eng.FromNative(extractData(result))}, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.HubspotAutomationSDK, name string) (sdk.HubspotAutomationEntity, error) {
	switch strings.ToLower(name) {
	case "actions_v4_collection_response_public_action_definition_forward":
		return client.ActionsV4CollectionResponsePublicActionDefinitionForward(nil), nil
	case "actions_v4_collection_response_public_action_function_identifier_no":
		return client.ActionsV4CollectionResponsePublicActionFunctionIdentifierNo(nil), nil
	case "actions_v4_collection_response_public_action_revision_forward":
		return client.ActionsV4CollectionResponsePublicActionRevisionForward(nil), nil
	case "actions_v4_public_action_definition":
		return client.ActionsV4PublicActionDefinition(nil), nil
	case "actions_v4_public_action_definition_requires_object":
		return client.ActionsV4PublicActionDefinitionRequiresObject(nil), nil
	case "actions_v4_public_action_function":
		return client.ActionsV4PublicActionFunction(nil), nil
	case "actions_v4_public_action_function_identifier":
		return client.ActionsV4PublicActionFunctionIdentifier(nil), nil
	case "actions_v4_public_action_revision":
		return client.ActionsV4PublicActionRevision(nil), nil
	case "automation_v4_api_flow":
		return client.AutomationV4ApiFlow(nil), nil
	case "automation_v4_batch_response_api_flow":
		return client.AutomationV4BatchResponseApiFlow(nil), nil
	case "automation_v4_batch_response_flow_id_workflow_id_mapping":
		return client.AutomationV4BatchResponseFlowIdWorkflowIdMapping(nil), nil
	case "automation_v4_collection_response_api_flow_email_campaign":
		return client.AutomationV4CollectionResponseApiFlowEmailCampaign(nil), nil
	case "automation_v4_collection_response_api_flow_listing_forward_paging":
		return client.AutomationV4CollectionResponseApiFlowListingForwardPaging(nil), nil
	case "automation_v4_collection_response_api_histogram_data_point_no":
		return client.AutomationV4CollectionResponseApiHistogramDataPointNo(nil), nil
	case "basic":
		return client.Basic(nil), nil
	case "callback":
		return client.Callback(nil), nil
	case "definition":
		return client.Definition(nil), nil
	case "email_templates_collection_response_public_folder_forward_paging":
		return client.EmailTemplatesCollectionResponsePublicFolderForwardPaging(nil), nil
	case "email_templates_collection_response_public_template_forward_paging":
		return client.EmailTemplatesCollectionResponsePublicTemplateForwardPaging(nil), nil
	case "email_templates_public_template":
		return client.EmailTemplatesPublicTemplate(nil), nil
	case "function":
		return client.Function(nil), nil
	case "sequence":
		return client.Sequence(nil), nil
	case "sequences_collection_response_with_total_public_sequence_lite":
		return client.SequencesCollectionResponseWithTotalPublicSequenceLite(nil), nil
	case "sequences_public_sequence":
		return client.SequencesPublicSequence(nil), nil
	case "sequences_public_sequence_enrollment":
		return client.SequencesPublicSequenceEnrollment(nil), nil
	case "sequences_public_sequence_enrollment_lite":
		return client.SequencesPublicSequenceEnrollmentLite(nil), nil
	case "sequences_public_sequence_performance":
		return client.SequencesPublicSequencePerformance(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// queryToMap converts a boru Value (Map or Scalar) into the
// `map[string]any` shape the SDK expects. Maps are unwrapped via
// eng.ToNative. Scalars are wrapped as {"id": <value>} so the
// shorthand `load 1 book` becomes `load {id:1} book`.
func queryToMap(v eng.Value) (map[string]any, error) {
	if v.Parent.ConformsTo(eng.TMap) {
		m, ok := eng.ToNative(v).(map[string]any)
		if !ok {
			return nil, fmt.Errorf("query map could not be unwrapped")
		}
		return m, nil
	}
	if v.Parent.ConformsTo(eng.TScalar) {
		return map[string]any{"id": eng.ToNative(v)}, nil
	}
	return nil, fmt.Errorf("query must be a Map or Scalar, got %s", v.Parent)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with the underlying record via .Data().
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}
