// Generated by sdkgen go-mcp target.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	sdk "github.com/voxgig-sdk/hubspot-automation-sdk/go"
)

// Args is the common argument shape for both tools. `entity` selects
// the SDK entity to operate on; `query` is the optional reqmatch /
// reqdata map passed through to the SDK. For load, `query` should be
// `{"id": <value>}`. For list, omit `query` or pass an empty map.
type Args struct {
	Entity string         `json:"entity" jsonschema:"actions_v4_collection_response_public_action_definition_forward | actions_v4_collection_response_public_action_function_identifier_no | actions_v4_collection_response_public_action_revision_forward | actions_v4_public_action_definition | actions_v4_public_action_definition_requires_object | actions_v4_public_action_function | actions_v4_public_action_function_identifier | actions_v4_public_action_revision | automation_v4_api_flow | automation_v4_batch_response_api_flow | automation_v4_batch_response_flow_id_workflow_id_mapping | automation_v4_collection_response_api_flow_email_campaign | automation_v4_collection_response_api_flow_listing_forward_paging | automation_v4_collection_response_api_histogram_data_point_no | basic | callback | definition | email_templates_collection_response_public_folder_forward_paging | email_templates_collection_response_public_template_forward_paging | email_templates_public_template | function | sequence | sequences_collection_response_with_total_public_sequence_lite | sequences_public_sequence | sequences_public_sequence_enrollment | sequences_public_sequence_enrollment_lite | sequences_public_sequence_performance"`
	Query  map[string]any `json:"query,omitempty" jsonschema:"optional match map e.g. {\"id\":1} for load, omit for list"`
}

func registerTools(server *mcp.Server, client *sdk.HubspotAutomationSDK) {
	mcp.AddTool(server, &mcp.Tool{
		Name: "hubspot-automation_list",
		Description: "List records from HubspotAutomation. " +
			"Args: entity (one of the supported SDK entities), query (optional filter map). " +
			"Returns the first page of records as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "list", args)
	})

	mcp.AddTool(server, &mcp.Tool{
		Name: "hubspot-automation_load",
		Description: "Load a single record from HubspotAutomation. " +
			"Args: entity, query ({\"id\":N} required). Returns the record as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "load", args)
	})
}

func runOp(client *sdk.HubspotAutomationSDK, op string, args Args) (*mcp.CallToolResult, any, error) {
	ent, err := entityFor(client, args.Entity)
	if err != nil {
		return toolError(err.Error())
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(args.Query, nil)
	case "load":
		result, err = ent.Load(args.Query, nil)
	default:
		return toolError(fmt.Sprintf("unknown op %q", op))
	}
	if err != nil {
		return toolError(err.Error())
	}

	// SDK returns *Entity wrappers; unwrap each via .Data() to get a
	// plain map[string]any (or []any of maps for list) suitable for
	// JSON marshalling.
	data := extractData(result)
	body, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return toolError(fmt.Sprintf("marshal: %v", err))
	}
	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: string(body)},
		},
	}, data, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.HubspotAutomationSDK, name string) (sdk.HubspotAutomationEntity, error) {
	switch strings.ToLower(name) {
	case "actions_v4_collection_response_public_action_definition_forward":
		return client.ActionsV4CollectionResponsePublicActionDefinitionForward(nil), nil
	case "actions_v4_collection_response_public_action_function_identifier_no":
		return client.ActionsV4CollectionResponsePublicActionFunctionIdentifierNo(nil), nil
	case "actions_v4_collection_response_public_action_revision_forward":
		return client.ActionsV4CollectionResponsePublicActionRevisionForward(nil), nil
	case "actions_v4_public_action_definition":
		return client.ActionsV4PublicActionDefinition(nil), nil
	case "actions_v4_public_action_definition_requires_object":
		return client.ActionsV4PublicActionDefinitionRequiresObject(nil), nil
	case "actions_v4_public_action_function":
		return client.ActionsV4PublicActionFunction(nil), nil
	case "actions_v4_public_action_function_identifier":
		return client.ActionsV4PublicActionFunctionIdentifier(nil), nil
	case "actions_v4_public_action_revision":
		return client.ActionsV4PublicActionRevision(nil), nil
	case "automation_v4_api_flow":
		return client.AutomationV4ApiFlow(nil), nil
	case "automation_v4_batch_response_api_flow":
		return client.AutomationV4BatchResponseApiFlow(nil), nil
	case "automation_v4_batch_response_flow_id_workflow_id_mapping":
		return client.AutomationV4BatchResponseFlowIdWorkflowIdMapping(nil), nil
	case "automation_v4_collection_response_api_flow_email_campaign":
		return client.AutomationV4CollectionResponseApiFlowEmailCampaign(nil), nil
	case "automation_v4_collection_response_api_flow_listing_forward_paging":
		return client.AutomationV4CollectionResponseApiFlowListingForwardPaging(nil), nil
	case "automation_v4_collection_response_api_histogram_data_point_no":
		return client.AutomationV4CollectionResponseApiHistogramDataPointNo(nil), nil
	case "basic":
		return client.Basic(nil), nil
	case "callback":
		return client.Callback(nil), nil
	case "definition":
		return client.Definition(nil), nil
	case "email_templates_collection_response_public_folder_forward_paging":
		return client.EmailTemplatesCollectionResponsePublicFolderForwardPaging(nil), nil
	case "email_templates_collection_response_public_template_forward_paging":
		return client.EmailTemplatesCollectionResponsePublicTemplateForwardPaging(nil), nil
	case "email_templates_public_template":
		return client.EmailTemplatesPublicTemplate(nil), nil
	case "function":
		return client.Function(nil), nil
	case "sequence":
		return client.Sequence(nil), nil
	case "sequences_collection_response_with_total_public_sequence_lite":
		return client.SequencesCollectionResponseWithTotalPublicSequenceLite(nil), nil
	case "sequences_public_sequence":
		return client.SequencesPublicSequence(nil), nil
	case "sequences_public_sequence_enrollment":
		return client.SequencesPublicSequenceEnrollment(nil), nil
	case "sequences_public_sequence_enrollment_lite":
		return client.SequencesPublicSequenceEnrollmentLite(nil), nil
	case "sequences_public_sequence_performance":
		return client.SequencesPublicSequencePerformance(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with its underlying record (via .Data()).
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}

func toolError(msg string) (*mcp.CallToolResult, any, error) {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{
			&mcp.TextContent{Text: msg},
		},
	}, nil, nil
}
